name = "SymKit"
uuid = "12345678-1234-1234-1234-123456789abc"  # Replace with your actual UUID
authors = ["Miraj Samarakkody <miraj.samarakkody@gmail.com>"]
version = "0.1.0"



[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SymKit = "7c8e681b-e4ae-4526-aa1a-1c81e092eb28"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
